package:
  name: grpcurl
  version: 1.9.3
  epoch: 0
  description: Basically curl for gRPC servers
  copyright:
    - license: MIT
  dependencies:
    runtime: []
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
    packages:
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://github.com/fullstorydev/grpcurl/releases/download/v${{package.version}}/grpcurl_${{package.version}}_linux_${{build.arch}}.tar.gz
      strip-components: 0
      expected-sha256: a926b62a85787ccf73ef8736b3ae554f1242e39d92bb8767a79d6dd23b11d1d5

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://github.com/fullstorydev/grpcurl/releases/download/v${{package.version}}/grpcurl_${{package.version}}_linux_arm64.tar.gz
      strip-components: 0
      expected-sha256: b20a00c1cb82ab81ec32696766d4076e99b4cb5ca0823a71767ba64dbea0f263

  - runs: |
      install -Dm755 grpcurl "${{targets.destdir}}/usr/bin/grpcurl"

update:
  enabled: true
  github:
    identifier: fullstorydev/grpcurl
    strip-prefix: v
    use-tag: true
