package:
  name: scapy
  version: 2.6.1
  epoch: 0
  description: Python-based interactive packet manipulation program and library
  copyright:
    - license: GPL-2.0-only
  dependencies:
    runtime:
      - python3
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - python3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/secdev/scapy
      tag: v${{package.version}}
      expected-commit: 8e08cbf759de6709a5b4af6bea3655d293129bb4

  - uses: python/install

update:
  enabled: true
  github:
    identifier: secdev/scapy
    strip-prefix: v
    use-tag: true
