package:
  name: trippy
  version: 0.13.0
  epoch: 0
  description: A network diagnostic tool combining traceroute and ping functionality
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime: []
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
    packages:
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://github.com/fujiapple852/trippy/releases/download/${{package.version}}/trippy-${{package.version}}-${{build.arch}}-unknown-linux-musl.tar.gz
      expected-sha256: aa2b7b2a0773f3cc04da691100419049950b690fe3736d25e24ac955b63d6056

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://github.com/fujiapple852/trippy/releases/download/${{package.version}}/trippy-${{package.version}}-${{build.arch}}-unknown-linux-musl.tar.gz
      expected-sha256: 73af939aa94e9e0f07cac2b3c8177e02a6b1c3be88299d85988e02be81ae7004

  - runs: |
      install -Dm755 trip "${{targets.destdir}}/usr/bin/trip"

update:
  enabled: true
  github:
    identifier: fujiapple852/trippy
    use-tag: true
