package:
  name: websocat
  version: 4.0.0
  epoch: 0
  description: Netcat, curl and socat for WebSockets
  copyright:
    - license: MIT
  dependencies:
    runtime: []
  target-architecture:
    - x86_64
    - aarch64

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
    packages:
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://github.com/vi/websocat/releases/download/v${{package.version}}-alpha3/websocat.${{build.arch}}-unknown-linux-musl
      extract: false
      expected-sha256: 924a39a86c50aeb0e5374ba2098391455b7997e43c1f9a2ea1ccd7e0eeb08eec

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://github.com/vi/websocat/releases/download/v${{package.version}}-alpha3/websocat.${{build.arch}}-unknown-linux-musl
      extract: false
      expected-sha256: a4ed418b149498596a4432daeb54c0867b94030123c4f713a40d218be112e1a9

  - runs: |
      install -Dm755 websocat.${{build.arch}}-unknown-linux-musl "${{targets.destdir}}/usr/bin/websocat"

update:
  enabled: true
  github:
    identifier: vi/websocat
    strip-prefix: v
    use-tag: true
